<div class="page-title">

    <div class="title-env">
        <h1 class="title">Все объявление</h1>
        <p class="description">Здесь отображаются все объявления. </p>
    </div>

    <div class="breadcrumb-env">

        <ol class="breadcrumb bc-1">
            <li>
                <a href="dashboard-1.html"><i class="fa-home"></i>Home</a>
            </li>
            <li>

                <a href="forms-native.html">Forms</a>
            </li>
            <li class="active">

                <strong>Form Wizard</strong>
            </li>
        </ol>

    </div>

</div>
<div class="row">
    <div class="col-xs-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Фильтр</h3>
                <div class="panel-options">
                </div>
            </div>
            <div class="panel-body">
                <form role="form">
                    <div class="row">
                        <div class="form-group col-xs-12 col-md-3">
                            <label class="control-label">Тип Сделки</label>

                            <script type="text/javascript">
                                jQuery(document).ready(function ($) {
                                    $("#sboxit-1").selectBoxIt();
                                });
                            </script>

                            <select class="form-control" id="sboxit-1" name="dtype">
                                <option value="">Выбрать тип</option>
                                <option <?= $this->params['dtype'] == 'prodazha' ? 'selected' : ''?>  value="prodazha">Продажа</option>
                                <option <?= $this->params['dtype'] == 'arenda' ? 'selected' : ''?> value="arenda">Аренда</option>
                            </select>

                        </div>

                        <div class="form-group col-xs-12 col-md-3">
                            <label class="control-label">Тип недвижимости</label>

                            <script type="text/javascript">
                                jQuery(document).ready(function ($) {
                                    $("#sboxit-2").selectBoxIt();
                                });
                            </script>

                            <select class="form-control" id="sboxit-2" name="ptype">
                                <option value="">Выбрать тип</option>
                                <option <?= $this->params['ptype'] == 'kvartira' ? 'selected' : ''?> value="kvartira">Квартира</option>
                                <option <?= $this->params['ptype'] == 'komnat' ? 'selected' : ''?> value="komnat">Комната</option>
                                <option <?= $this->params['ptype'] == 'domov' ? 'selected' : ''?> value="domov">Дом</option>
                            </select>

                        </div>

                        <div class="form-group col-xs-12 col-md-3">
                            <label class="control-label">Район</label>

                            <script type="text/javascript">
                                jQuery(document).ready(function ($) {
                                    $("#sboxit-3").selectBoxIt();
                                });
                            </script>

                            <select class="form-control" id="sboxit-3" name="district">
                                <option value="">Выбрать район</option>
                                <? foreach ($this->districts as $district): ?>
                                    <option <?= $this->params['district'] == $district->getId() ? 'selected' : ''?> value="<?= $district->getId() ?>"><?= $district->getName() ?></option>
                                <? endforeach; ?>
                            </select>

                        </div>

                        <div class="form-group col-xs-12 col-md-3">
                            <label class="control-label">Микрорайон</label>

                            <script type="text/javascript">
                                jQuery(document).ready(function ($) {
                                    $("#sboxit-4").selectBoxIt();
                                });
                            </script>
                            <select class="form-control" id="sboxit-4" name="microdistrict">
                                <option class="def" value="">Выбрать микрорайон</option>
                                <? if(is_array($this->microdistricts)){
                                 foreach ($this->microdistricts as $id => $name): ?>
                                    <option <?= $this->params['microdistrict'] == $id ? 'selected' : ''?> value="<?= $id ?>"><?= $name ?></option>
                                <? endforeach; }?>
                            </select>

                        </div>
                    </div>
                    <div class="row x-select-wrap ">
                        <div class="form-group col-xs-12 col-md-3">
                            <label class="control-label">К-во комнат</label>
                            <div id="rooms" data-default="Комнат" data-parent="rooms"
                                 class="x-select-item-wrap checker col-xs-12">
                                <div value="null" class="x-select">Комнат</div>
                                <div class="x-select-tt">

                                    <?
                                        for ($i = 1; $i <= 6; $i++) {
                                            $j = $i == 6 ? '6+' : $i;
                                            if ($this->params['rooms']) {
                                                $checked = in_array($i, $this->params['rooms']) ? 'checked' : '';
                                                $result .= '<div data-value="' . $i . '" class="x-select-tt-item ' . $checked . '">' . $j . ' комнатная</div>';
                                            } else {
                                                $result .= '<div data-value="' . $i . '" class="x-select-tt-item">' . $j . ' комнатная</div>';
                                            }

                                        }
                                        echo $result;
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <div class="row">
                                <div class="form-group col-xs-6">
                                    <label class="control-label">Цена От</label>
                                    <input type="text" class="form-control" name="pricefrom" placeholder="От"
                                        <?= $this->params['pricefrom'] ? 'value="'. $this->params['pricefrom'] .'"' : ''?>>
                                </div>
                                <div class="form-group col-xs-6">
                                    <label class="control-label">Цена До</label>
                                    <input type="text" class="form-control" id="priceto" name="priceto" placeholder="До"
                                        <?= $this->params['priceto'] ? 'value="'. $this->params['priceto'] .'"' : ''?>>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-md-1">
                            <label class="control-label">Валюта</label>

                            <script type="text/javascript">
                                jQuery(document).ready(function ($) {
                                    $("#sboxit-currency").selectBoxIt();
                                });
                            </script>

                            <select class="form-control" id="sboxit-currency" name="currency">
                                <option <?= $this->params['currency'] == 'USD' ? 'selected' : ''?>>USD</option>
                                <option <?= $this->params['currency'] == 'UAH' ? 'selected' : ''?>>UAH</option>
                                <option <?= $this->params['currency'] == 'EUR' ? 'selected' : ''?>>EUR</option>
                            </select>
                        </div>

                        <div class="form-group col-xs-12 col-md-2">
                            <div class="row">
                                <div class="col-xs-9" style="padding-right: 0;">
                                    <label class="control-label">Поиск по ID</label>
                                    <input type="text" class="form-control" name="byid" placeholder="Введите ID"
                                        <?= $this->params['id'] ? 'value="'. $this->params['id'] .'"' : ''?>>
                                </div>
                                <div class="col-xs-3" style="padding-left: 0; margin-top: 23px;">
                                    <button class="btn btn-icon btn-success byid" style="height: 32px;">
                                        <i class="fa-search" style="padding: 0;"></i>
                                    </button>
                                </div>
                            </div>

                        </div>
                        <div class="form-group col-xs-12 col-md-3" style="margin-top: 30px;">
                            <div class="row">
                                <div class="col-xs-5">
                                    <a href="#" data-action="search"
                                       class="btn btn-secondary btn-icon btn-icon-standalone">
                                        <i class="fa-filter"></i>
                                        <span>Показать</span>
                                    </a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="/admin/listings" class="btn btn-red btn-icon btn-icon-standalone">
                                        <i class="fa-remove"></i>
                                        <span>Сбросить фильтр</span>
                                    </a>
                                </div>


                            </div>

                        </div>

                    </div>


                </form>

            </div>
        </div>

    </div>
</div>

<div class="listings_wrap row">
    <?
    foreach ($this->listings as $listing) :
        $params = [];

        foreach ($listing->getParamsValue() as $k => $paramValue) {
            if (is_int($k)) {
                $params[$paramValue->getParam()->getParamKey()] = $paramValue->getValue();
            }
        }
        ?>
        <div class="col-xs-12 listing_wrap" data-id="<?= $listing->getId() ?>">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-2 image_wrap">
                    <img src="<?= count($listing->getImages()) > 0 ? $listing->getImages()[0]->getThumbLink() : '/assets/images/noimage.jpg' ?>"/>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-5 data_wrap">
                    <div class="status_wrap">

                    </div>
                    <h4>
                        <a href="/listing/<?= $listing->getId() ?>" target="_blank"> <?= $listing->getStreet() ?>
                            , <?= $listing->getHouseNumber() ?></a>
                    </h4>

                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p>Операция: <?= $listing->getDealType()->getName() ?></p>
                            <p>Цена: <?= $listing->getPrice() ?> <?= $listing->getCurrency()->getSign() ?></p>
                            <p>Телефон: <?= $listing->getPhones()[0]->getNumber() ?> </p>
                            <p><?= $listing->getPropertyType()->getName() ?>
                                , <?= $params['q_rooms'] ?> <?= $params['q_rooms'] < 5 ? $params['q_rooms'] == 1 ? 'комната' : 'комнаты' : 'комнат' ?> </p>
                            <p>Площадь: <?= $params['common_square'] !== '' ? $params['common_square'] : '?' ?>
                                /<?= $params['real_square'] !== '' ? $params['real_square'] : '?' ?>
                                /<?= $params['kitchen_square'] !== '' ? $params['kitchen_square'] : '?' ?> </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <p>ID: <?= $listing->getId() ?> </p>
                            <p>Район: <?= $listing->getMicrodistrict()->getDistrict()->getName() ?></p>
                            <p>Микрорайон: <?= $listing->getMicrodistrict()->getName() ?></p>

                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-2 dates_wrap text-center">
                    <p>Добавлено</p>
                    <span><?= $listing->getDateAdd() ?></span>
                    <p>Редактировано</p>
                    <span><?= $listing->getDateEdit() ?></span>
                    <p>Прозвон</p>
                    <span><?= $listing->getDateCall() ?></span>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 text-center">
                    <div class="btn-group">
                        <a href="listings/edit/<?= $listing->getId() ?>" class="btn btn-success">Редактировать</a>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                                aria-expanded="false"><span
                                    class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-green" role="menu">
                            <li><a href="#">Деактивировать</a></li>
                            <li><a href="#" data-action="delete">Удалить</a></li>
                            <li><a href="#">Прозвон</a></li>
                            <li><a href="#" data-action="update">Обновить</a></li>
                            <!--                            <li class="divider"></li>-->
                            <!--                            <li><a href="#">Separated link</a></li>-->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <?endforeach;?>
</div>

<?
if(!$this->params['id'])
{
    echo $this->paginationControl($this->listings,
        'Sliding',
        'admin/partial/paginator',
        ['route' => 'listings', 'query' => $this->params]);
}
 ?>

<script>
    $(document).on('click', '.dropdown-menu li a', function (e) {
        e.preventDefault();
        var action = $(this).data('action');
        var id = $(this).closest(".listing_wrap").data("id");
        if (action == 'delete') {
            swal({
                title: "Вы уверены?",
                text: "Объявление будет полностью удалено!",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: true,
                confirmButtonText: "Да",
                cancelButtonText: "Отмена",
                confirmButtonColor: "#ec6c62"
            }, function () {
                console.log("confirmed");
                $.ajax({
                    url: "",
                    type: "POST",
                    data: 'delete&id=' + id,
                    success: function (res) {
                        if (res == 'success')
                            window.location.reload();
                    }
                });
            });

        }
        if (action == 'update') {
            $.ajax({
                url: "",
                type: "POST",
                data: 'update&id=' + id,
                success: function (res) {
                    console.log(res);
                    if (res == 'success')
                        window.location.reload();
                }
            });
        }
    });

    $(document).ready(function () {
        $($('.panel-body form')[0]).xSelect();
        $('.byid').click(function (e) {
            e.preventDefault();
            var id = $('input[name="byid"]').val();
            if(id !== '')
                window.location.href = '/admin/listings?id='+id;
        });
        $('select[name="district"]').change(function () {
            var district = $(this).val();
            $.ajax({
                type : 'post',
                url : '',
                data : {getMicrodistrict : 1,district:district},
                dataType : 'json',
                success : function (res) {
                    $('select[name="microdistrict"] option').not('.def').remove();
                    $.each(res, function (id,name) {
                        $('select[name="microdistrict"]').data("selectBox-selectBoxIt").add({ value: id, text: name });
                    });
                },
                error : function (err) {
                    console.log(err);
                }
            });
        });
        slink();
        $('select,input').change(function () {
            slink();
        });
        $('.x-select-tt-item').click(function () {
            slink();
        });
    });//End of document ready

    function slink() {
        var sb = $('a.btn[data-action="search"]'); //search button
        var qs = '' //query string
        var filter = {};
        filter['rooms'] = [];

        $.each(checker_container.rooms, function () {
            filter.rooms.push(parseInt(this));
        });
        $.each($('select'), function () {
            var name = $(this).attr('name');
            var value = $(this).val();
            if (value) {
                filter[name] = value;
            }

        });
        $.each($('input'), function () {
            if ($(this).attr('name') == 'byid' || $(this).attr('type') == 'checkbox')
                return;
            var name = $(this).attr('name');
            var value = $(this).val();
            if (value) {
                filter[name] = value;
            }
        });

        if (!filter.pricefrom && !filter.priceto)
            delete filter.currency;
        if (filter.rooms.length == 0)
            delete filter.rooms;
        if(Object.keys(filter).length > 0)
            qs += '?search=1';
        $.each(filter, function (name, value) {
            if (name == 'rooms')
                return;

            qs += (qs == '' ? name + '=' + value : '&' + name + '=' + value);
        });

        $.each(filter, function (name, value) {
            if (name !== 'rooms')
                return;

            $.each(value, function () {
                qs += (qs == '' ? 'rooms=' + this : '&rooms=' + this);
            });
        });
        <?
//            if($this->page > 1)
//            {
//                echo "qs += (qs == '' ? 'page=' + ". $this->page ." : '&page=' + ". $this->page .");";
//            }
        ?>
        sb.attr('href', '/admin/listings'+qs);
    }
</script>

<link rel="stylesheet" href="/lib/x-select/css/x-select.css">
<style>
    .x-select-item-wrap {
        border: 1px solid #e4e4e4;
        font-size: 1.3rem;
        line-height: 13px;
        margin: 0;
        font: 13px Helvetica, Arial;
        color: #7d7f7f;
    }

    .x-select-item-wrap.checker .x-select-tt-item:before {
        background: url(/assets/images/cbx-sprite-green.png) no-repeat;
        width: 16px;
        height: 16px;
        background-size: 32px;
        background-position: -16px;
    }

</style>

<script src="/assets/js/jquery-ui/jquery-ui.min.js"></script>
<script src="https://redl.com.ua/assets/js/selectboxit/jquery.selectboxit.min.js"></script>
<script src="/lib/x-select/js/x-select.new.js"></script>

