<div class="page-title">

    <div class="title-env">
        <h1 class="title">Все объявление</h1>
        <p class="description">Здесь отображаются все объявления. </p>
    </div>

    <div class="breadcrumb-env">

        <ol class="breadcrumb bc-1">
            <li>
                <a href="dashboard-1.html"><i class="fa-home"></i>Home</a>
            </li>
            <li>

                <a href="forms-native.html">Forms</a>
            </li>
            <li class="active">

                <strong>Form Wizard</strong>
            </li>
        </ol>

    </div>

</div>
<div class="row">
    <div class="col-xs-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Фильтр</h3>
                <div class="panel-options">
                    <a href="#" data-toggle="panel">
                        <span class="collapse-icon">&ndash;</span>
                        <span class="expand-icon">+</span>
                    </a>
                </div>
            </div>
            <div class="panel-body">

                <form role="form" class="row">

                    <div class="form-group col-xs-12 col-md-3">
                        <label class="control-label">Тип Сделки</label>

                        <script type="text/javascript">
                            jQuery(document).ready(function($)
                            {
                                $("#sboxit-1").selectBoxIt({
                                    showFirstOption: false
                                }).on('open', function()
                                {
                                    // Adding Custom Scrollbar
                                    $(this).data('selectBoxSelectBoxIt').list.perfectScrollbar();
                                });
                            });
                        </script>

                        <select class="form-control" id="sboxit-1">
                            <option>Выбрать тип</option>
                            <option value="au">Продажа</option>
                            <option value="bd">Аренда</option>
                        </select>

                    </div>

                    <div class="form-group col-xs-12 col-md-3">
                        <label class="control-label">Тип недвижимости</label>

                        <script type="text/javascript">
                            jQuery(document).ready(function($)
                            {
                                $("#sboxit-2").selectBoxIt({
                                    showFirstOption: false
                                }).on('open', function()
                                {
                                    // Adding Custom Scrollbar
                                    $(this).data('selectBoxSelectBoxIt').list.perfectScrollbar();
                                });
                            });
                        </script>

                        <select class="form-control" id="sboxit-2">
                            <option>Выбрать тип</option>
                            <option value="al">Квартира</option>
                            <option value="au">Комната</option>
                            <option value="bd">Дом</option>
                        </select>

                    </div>

                    <div class="form-group col-xs-12 col-md-3">
                        <label class="control-label">Native dropdown menu</label>

                        <script type="text/javascript">
                            jQuery(document).ready(function($)
                            {
                                $("#sboxit-3").selectBoxIt({
                                    showFirstOption: false,
                                    "native": true
                                });
                            });
                        </script>

                        <select class="form-control" id="sboxit-3">
                            <option>Select your country</option>
                            <option value="al">Albania</option>
                            <option value="au">Australia</option>
                            <option value="bd">Bandgladesh</option>
                            <option value="br">Brasil</option>
                            <option value="ca">Canada</option>
                            <option value="cn">China</option>
                            <option value="de">Germany</option>
                            <option value="fr">France</option>
                            <option value="gr">Greece</option>
                            <option value="jp">Japan</option>
                            <option value="xk">Kosovo</option>
                            <option value="nl">Netherlands</option>
                            <option value="no">Norway</option>
                            <option value="ru">Russia</option>
                            <option value="se">Sweden</option>
                            <option value="tr">Turkey</option>
                            <option value="uk">United Kingdom</option>
                            <option value="us">United States</option>
                        </select>

                    </div>

                    <div class="form-group col-xs-12 col-md-3">
                        <label class="control-label">Show and hide with effects</label>

                        <script type="text/javascript">
                            jQuery(document).ready(function($)
                            {
                                $("#sboxit-4").selectBoxIt({
                                    showEffect: 'fadeIn',
                                    hideEffect: 'fadeOut'
                                });
                            });
                        </script>

                        <select class="form-control" id="sboxit-4">
                            <option>Select your country</option>
                            <option value="al">Albania</option>
                            <option value="au">Australia</option>
                            <option value="bd">Bandgladesh</option>
                            <option value="br">Brasil</option>
                            <option value="ca">Canada</option>
                            <option value="cn">China</option>
                            <option value="de">Germany</option>
                            <option value="fr">France</option>
                            <option value="gr">Greece</option>
                            <option value="jp">Japan</option>
                            <option value="xk">Kosovo</option>
                            <option value="nl">Netherlands</option>
                            <option value="no">Norway</option>
                            <option value="ru">Russia</option>
                            <option value="se">Sweden</option>
                            <option value="tr">Turkey</option>
                            <option value="uk">United Kingdom</option>
                            <option value="us">United States</option>
                        </select>

                    </div>

                </form>

            </div>
        </div>

    </div>
</div>


<div class="listings_wrap row">
    <?
    foreach ($this->listings as $listing) {
        $params = [];
        foreach ($listing->getParamsValue() as $k => $paramValue) {

            if(is_int($k))
            {
                $params[$paramValue->getParam()->getParamKey()] = $paramValue->getValue();
            }
        }
        ?>
        <div class="col-xs-12 listing_wrap" data-id="<?=$listing->getId()?>">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-2 image_wrap">
                    <img src="<?= count($listing->getImages()) > 0 ? $listing->getImages()[0]->getThumbLink() : '/assets/images/noimage.jpg' ?>"/>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-5 data_wrap">
                    <div class="status_wrap">

                    </div>
                    <h4>
                        <a href="/listing/<?=$listing->getId()?>" target="_blank"> <?= $listing->getStreet() ?>, <?= $listing->getHouseNumber() ?></a>
                    </h4>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p>Операция: <?= $listing->getDealType()->getName() ?></p>
                            <p>Цена: <?= $listing->getPrice() ?> <?= $listing->getCurrency()->getSign() ?></p>
                            <p>Телефон: <?= $listing->getPhones()[0]->getNumber() ?> </p>
                            <p><?= $listing->getPropertyType()->getName() ?>
                                , <?= $params['q_rooms'] ?> <?= $params['q_rooms'] < 5 ? $params['q_rooms'] == 1 ? 'комната' : 'комнаты' : 'комнат' ?> </p>
                            <p>Площадь: <?= $params['common_square'] !== '' ? $params['common_square'] : '?' ?>
                                /<?= $params['real_square'] !== '' ? $params['real_square'] : '?' ?>
                                /<?= $params['kitchen_square'] !== '' ? $params['kitchen_square'] : '?' ?> </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <p>ID: <?= $listing->getId() ?> </p>
                            <p>Район: <?= $listing->getMicrodistrict()->getDistrict()->getName() ?></p>
                            <p>Микрорайон: <?= $listing->getMicrodistrict()->getName() ?></p>

                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-2 dates_wrap text-center">
                    <p>Добавлено</p>
                    <span><?= $listing->getDateAdd() ?></span>
                    <p>Редактировано</p>
                    <span><?= $listing->getDateEdit() ?></span>
                    <p>Прозвон</p>
                    <span><?= $listing->getDateCall() ?></span>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 text-center">
                    <div class="btn-group">
                        <a href="listings/edit/<?= $listing->getId() ?>" class="btn btn-success">Редактировать</a>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                                aria-expanded="false"><span
                                    class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-green" role="menu">
                            <li><a href="#">Деактивировать</a></li>
                            <li><a href="#" data-action="delete">Удалить</a></li>
                            <li><a href="#">Прозвон</a></li>
                            <li><a href="#" data-action="update">Обновить</a></li>
<!--                            <li class="divider"></li>-->
<!--                            <li><a href="#">Separated link</a></li>-->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <?
    }
    ?>
</div>

<script>
    $(document).on('click','.dropdown-menu li a',function (e) {
        e.preventDefault();
        var action = $(this).data('action');
        var id = $(this).closest(".listing_wrap").data("id");
        if (action == 'delete')
        {
            swal({
                title: "Вы уверены?",
                text: "Объявление будет полностью удалено!",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: true,
                confirmButtonText: "Да",
                cancelButtonText: "Отмена",
                confirmButtonColor: "#ec6c62"
            }, function() {
                console.log("confirmed");
                $.ajax({
                    url: "",
                    type: "POST",
                    data: 'delete&id='+id,
                    success:function (res) {
                        if(res == 'success')
                            window.location.reload();
                    }
                });
            });

        }
        if(action == 'update')
        {
            $.ajax({
                url: "",
                type: "POST",
                data: 'update&id='+id,
                success:function (res) {
                    console.log(res);
                    if(res == 'success')
                        window.location.reload();
                }
            });
        }
    });

    $(document).ready(function () {

    });//End of document ready
</script>

<script src="/assets/js/jquery-ui/jquery-ui.min.js"></script>
<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"></script>
