
  <?
  foreach ($this->form->get('crop')->getValue() as $k=>$v)
  {
      $crops[$k] = json_decode($v,true);
  }


  ?>

<div class="page-title">

    <div class="title-env">
        <h1 class="title"><?= $this->isEdit ? 'Редактировать объявление' : 'Добавить объявление' ?></h1>
        <p class="description">Здесь вы можете <?= $this->isEdit ? 'отредактировать' : 'добавить новое' ?> объявление. Не забудтье заполнить все обязательные
            поля. </p>
    </div>

    <div class="breadcrumb-env">

        <ol class="breadcrumb bc-1">
            <li>
                <a href="dashboard-1.html"><i class="fa-home"></i>Home</a>
            </li>
            <li>

                <a href="forms-native.html">Forms</a>
            </li>
            <li class="active">

                <strong>Form Wizard</strong>
            </li>
        </ol>

    </div>

</div>

<?= $this->form()->openTag($form); ?>
<div id="rootwizard" class="form-wizard">
    <ul class="tabs">
        <li id="to1" class="completed">
            <a href="#fwv-1" data-toggle="tab">
                Основная информация
                <span>1</span>
            </a>
        </li>
        <li id="to2" class="">
            <a href="#fwv-2" data-toggle="tab">
                Дополнительная информация
                <span>2</span>
            </a>
        </li>
        <li class="tab3 active">
            <a href="#fwv-3" data-toggle="tab">
                Фотографии
                <span>3</span>
            </a>
        </li>
    </ul>

    <div class="progress-indicator">
        <span></span>
    </div>

    <div class="tab-content no-margin">
        <!-- Tabs Content -->
        <div class="tab-pane with-bg active" id="fwv-1">
            <div class="row image_grid">
                <div class="col-xs-12">
                    <div class="form-group <?= $this->formElementErrors($form->get('listing_images')) !== '' ? 'has-error' : '' ?>">
                        <div class="input-file-wrap">
                            <?= $this->formElement($form->get('listing_images')); ?>
                            <?= $this->formLabel($form->get('listing_images')); ?>
                        </div>
                        <?= $this->formElementErrors($form->get('listing_images')); ?>
                    </div>
                </div>
                <div class="col-xs-12 preview-wrap">

                </div>
                <div class="col-xs-12">
                    <ul class="pager wizard">
                        <li class="previous">
                            <a href="#"><i class="entypo-left-open"></i> Предидущий шаг</a>
                        </li>
                        <li class="next"><a href="#"><?= $this->isEdit ? 'Сохранить изменения' : 'Добавить объявление' ?> <i class="entypo-right-open"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js"></script>
<script>
    $(document).ready(function () {

        var el = $('.form-wizard'),
            $tabs = el.find('> ul > li'),
            $progress = el.find('.progress-indicator'),
            _index = el.find('ul li.active').index();

        if(_index > 0) {
            $progress.css({width: _index / $tabs.length * 100 + '%'});
            $tabs.removeClass('completed').slice(0, _index).addClass('completed');
        }

        $('.btn-loading').click(function (e) {
            e.preventDefault();
        });

        $('.next a, .tab3').click(function (e) {
            e.preventDefault();
            var fd = new FormData;

            for(i=0;i<fileContainer.length;i++)
            {
                if(typeof(fileContainer[i].image) == 'string')
                {
                    fd.append('old_listing_images[]',fileContainer[i].image);
                    fd.append('old_crop[]',fileContainer[i].crop);
                    fd.append('order[]',i);
                }
                else
                {
                    fd.append('listing_images[]',fileContainer[i].image);
                    fd.append('crop[]',fileContainer[i].crop);
                    fd.append('order[]',i);
                }

            }
//            console.log(fd);
//            return;

            $.ajax({
                url: '',
                type: "POST",
                data: fd,
                processData: false,
                contentType: false,
                beforeSend: function () {
                    $("li.next a").addClass("btn-loading");
                },
                success: function (res) {
                    try {
                        res = JSON.parse(res);
                    } catch (e) {
                        console.log(res);
                    }
                    if (res.success) {
                        window.location.href = '/admin/listings';
                    }
                    else {
                        if (res.mimeError) {
                            swal('Ошибка файла', res.mimeError, 'error');
                        }
                        if (res.sizeError) {
                            swal('Ошибка в размере изображения', res.sizeError, 'error');
                        }
                    }

//                    console.log(res);
                },
                error : function (err) {
                    console.log(err.responseText);
                }
            });
        });
        $('#to2,.previous').click(function () {
            swal({
                    title: "Вы уверены?",
                    text: "Все данные введенные на этом этапе не сохранятся",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Да, уверен!",
                    cancelButtonText: "Отмена",
                    closeOnConfirm: false
                },
                function(){
                    window.location.href = '?step=2';
                });
        });
        $('#to1').click(function () {
            swal({
                    title: "Вы уверены?",
                    text: "Все данные введенные на этом этапе не сохранятся",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Да, уверен!",
                    cancelButtonText: "Отмена",
                    closeOnConfirm: false
                },
                function(){
                    window.location.href = '?step=1';
                });
        });

        fileContainer = [];

        if(JSON.parse('<?=json_encode($this->form->get('listing_images')->getValue())?>'))
        {
            images = JSON.parse('<?=json_encode($this->form->get('listing_images')->getValue())?>');
            crops = JSON.parse('<?=json_encode($crops)?>');

            for(i = 0; i < images.length; i++)
            {
                fileContainer.push({image:images[i],crop:crops[i],order:i});
            }
            drowPreview();
        }


        $(document).on('change', 'input[type="file"]', function () {
            if(fileContainer.length == 0)
            {
                $.map(this.files,function (v,k) {
                    fileContainer[k] = {image:v};
                });
            }
            else
            {
                var tmp = [];
                $.map(this.files,function (v,k) {
                    tmp[k] = {image:v};
                });
                fileContainer = $.merge(fileContainer,tmp);
            }

            drowPreview();
        });

        $(document).on('click','.remove_image',function () {
            var key = $(this).data('key');
            fileContainer.splice(key,1);
            drowPreview();
        });

        function drowPreview() {
            if (fileContainer.length > 0) {
                var preview = $('.preview-wrap');
                var reader = new FileReader();
                preview.empty();

                drowImg(0, reader, preview);
            }
        }

        function drowImg(step, reader, preview) {
            limit = fileContainer.length;
            if (step < limit) {
                if(typeof(fileContainer[step].image) == 'string')
                {
                    preview.append('<div class="preview-item-wrap" data-item="' + step + '"><div class="preview-image-wrap"><img src="' + fileContainer[step].image + '"/></div><span class="remove_image" data-key="' + step + '"><i class="fa fa-times" aria-hidden="true"></i></span></div>');
                    var data = (typeof(fileContainer[step].crop) == 'string' ? JSON.parse(fileContainer[step].crop) : fileContainer[step].crop);
                    doCrop($('.preview-item-wrap[data-item="' + step + '"]').find('img')[0],data);
                    step++;
                    if (step < limit) {
                        drowImg(step, reader, preview);
                    }
                }
                else
                {
                    reader.readAsDataURL(fileContainer[step].image)
                    reader.onloadend = function (e) {
                        preview.append('<div class="preview-item-wrap" data-item="' + step + '"><div class="preview-image-wrap"><img src="' + e.target.result + '"/></div><span class="remove_image" data-key="' + step + '"><i class="fa fa-times" aria-hidden="true"></i></span></div>');
                        doCrop($('.preview-item-wrap[data-item="' + step + '"]').find('img')[0],null);
                        step++;
                        if (step < limit) {
                            drowImg(step, reader, preview);
                        }
                    };
                }
            }
        }

        function doCrop(image,data) {
            var cropper = new Cropper(image, {
                aspectRatio: 8 / 5,
                autoCropArea: 1,
                data: data,
                viewMode: 2,
                zoomable: false,
                toggleDragModeOnDblclick: false,
                crop: function (e) {
                    var index = $(image.closest('.preview-item-wrap')).data('item');
                    fileContainer[index].crop = JSON.stringify(e.detail);
                }

            });
        }

        function reorderPreview() {
//            console.log(fileContainer);
            var newOrder = [];
            var preview = $('.preview-wrap');
            for(i=0;i<$('.preview-item-wrap').length;i++)
            {
                var index =$($('.preview-item-wrap')[i]).attr('data-item');
                newOrder[i] = fileContainer[index];
            }

            fileContainer = newOrder;
            drowPreview();
        }

            if($(".preview-wrap").sortable('instance'))
                $(".preview-wrap").sortable('destroy');

            $('.preview-wrap').sortable({
                update : function () {
                    reorderPreview();
            }
            });
    });//End of document ready
</script>

<link rel="stylesheet" href="/assets/css/dropzone.css">
<link rel="stylesheet" href="/assets/css/my-dropzone.css">
<link rel="stylesheet" href="/assets/js/cropper/cropper.min.css">
<link rel="stylesheet" href="/assets/js/jquery-ui/jquery-ui.min.css">

<script src="/assets/js/jquery-ui/jquery-ui.min.js"></script>
<script src="/assets/js/dropzone.js"></script>
<script src="/assets/js/cropper/cropper.min.js"></script>

