<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Redl')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet($this->basePath('/assets/css/fonts/linecons/css/linecons.css'))
            ->appendStylesheet($this->basePath('/assets/css/fonts/fontawesome/css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('/assets/css/bootstrap.css'))
            ->appendStylesheet($this->basePath('/assets/css/xenon-core.css'))
            ->appendStylesheet($this->basePath('/assets/css/xenon-forms.css'))
            ->appendStylesheet($this->basePath('/assets/css/xenon-components.css'))
            ->appendStylesheet($this->basePath('/assets/css/xenon-skins.css'))
            ->appendStylesheet($this->basePath('/assets/css/xenon-custom.css'))
            ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css")
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('/assets/js/jquery-1.11.1.min.js'))
        ?>
    </head>
    <body class="page-body">

    <div class="settings-pane">

        <a href="#" data-toggle="settings-pane" data-animate="true">
            &times;
        </a>

        <div class="settings-pane-inner">

            <div class="row">

                <div class="col-md-4">

                    <div class="user-info">

                        <div class="user-image">
                            <a href="extra-profile.html">
                                <img src="/assets/images/user-2.png" class="img-responsive img-circle" />
                            </a>
                        </div>

                        <div class="user-details">

                            <h3>
                                <a href="extra-profile.html">John Smith</a>

                                <!-- Available statuses: is-online, is-idle, is-busy and is-offline -->
                                <span class="user-status is-online"></span>
                            </h3>

                            <p class="user-title">Web Developer</p>

                            <div class="user-links">
                                <a href="extra-profile.html" class="btn btn-primary">Edit Profile</a>
                                <a href="extra-profile.html" class="btn btn-success">Upgrade</a>
                            </div>

                        </div>

                    </div>

                </div>

                <div class="col-md-8 link-blocks-env">

                    <div class="links-block left-sep">
                        <h4>
                            <span>Notifications</span>
                        </h4>

                        <ul class="list-unstyled">
                            <li>
                                <input type="checkbox" class="cbr cbr-primary" checked="checked" id="sp-chk1" />
                                <label for="sp-chk1">Messages</label>
                            </li>
                            <li>
                                <input type="checkbox" class="cbr cbr-primary" checked="checked" id="sp-chk2" />
                                <label for="sp-chk2">Events</label>
                            </li>
                            <li>
                                <input type="checkbox" class="cbr cbr-primary" checked="checked" id="sp-chk3" />
                                <label for="sp-chk3">Updates</label>
                            </li>
                            <li>
                                <input type="checkbox" class="cbr cbr-primary" checked="checked" id="sp-chk4" />
                                <label for="sp-chk4">Server Uptime</label>
                            </li>
                        </ul>
                    </div>

                    <div class="links-block left-sep">
                        <h4>
                            <a href="#">
                                <span>Help Desk</span>
                            </a>
                        </h4>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#">
                                    <i class="fa-angle-right"></i>
                                    Support Center
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa-angle-right"></i>
                                    Submit a Ticket
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa-angle-right"></i>
                                    Domains Protocol
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa-angle-right"></i>
                                    Terms of Service
                                </a>
                            </li>
                        </ul>
                    </div>

                </div>

            </div>

        </div>

    </div>

    <div class="page-container">
        <!-- add class "sidebar-collapsed" to close sidebar by default, "chat-visible" to make chat appear always -->

        <!-- Add "fixed" class to make the sidebar fixed always to the browser viewport. -->
        <!-- Adding class "toggle-others" will keep only one menu item open at a time. -->
        <!-- Adding class "collapsed" collapse sidebar root elements and show only icons. -->
        <div class="sidebar-menu toggle-others fixed">

            <div class="sidebar-menu-inner">

                <header class="logo-env">

                    <!-- logo -->
                    <div class="logo">
<!--                        <a href="dashboard-1.html" class="logo-expanded">-->
<!--                            <img src="/assets/images/logo@2x.png" width="80" alt="" />-->
<!--                        </a>-->
<!---->
<!--                        <a href="dashboard-1.html" class="logo-collapsed">-->
<!--                            <img src="/assets/images/logo-collapsed@2x.png" width="40" alt="" />-->
<!--                        </a>-->

                        <h1 style="margin: 0; color: #ffffff;">Redl</h1>
                    </div>

                    <!-- This will toggle the mobile menu and will be visible only on mobile devices -->
                    <div class="mobile-menu-toggle visible-xs">
                        <a href="#" data-toggle="user-info-menu">
                            <i class="fa-bell-o"></i>
                            <span class="badge badge-success">7</span>
                        </a>

                        <a href="#" data-toggle="mobile-menu">
                            <i class="fa-bars"></i>
                        </a>
                    </div>

                    <!-- This will open the popup with user profile settings, you can use for any purpose, just be creative -->
<!--                    <div class="settings-icon">-->
<!--                        <a href="#" data-toggle="settings-pane" data-animate="true">-->
<!--                            <i class="linecons-cog"></i>-->
<!--                        </a>-->
<!--                    </div>-->


                </header>

                <?php
                $this->mainMenu()->setItems([
                    [
                        'id' => 'menu_listings',
                        'label' => 'Объявления',
                        'icon' => 'linecons-cog',
                        'link' => '#',
                        'dropdown' => [
                            [
                                'id' => 'menu_all',
                                'label' => 'Все объявление',
                                'link' => '/admin/listings'
                            ],
                            [
                                'id' => 'menu_add',
                                'label' => 'Добавить объявление',
                                'link' => '/admin/listings/add'
                            ],
                        ],
                    ],
                    [
                        'id' => 'menu_phones',
                        'label' => 'Управление телефонами',
                        'icon' => 'linecons-star',
                        'link' => '#'
                    ],
                ]);
                $this->mainMenu()->setActiveItemId($this->activeMenuItem);

                echo $this->mainMenu()->render();
                ?>
             </div>

        </div>

        <div class="main-content">

            <!-- User Info, Notifications and Menu Bar -->
            <nav class="navbar user-info-navbar" role="navigation">

                <!-- Left links for user info navbar -->
                <ul class="user-info-menu left-links list-inline list-unstyled">

                    <li class="hidden-sm hidden-xs">
                        <a href="#" data-toggle="sidebar">
                            <i class="fa-bars"></i>
                        </a>
                    </li>

                </ul>


                <!-- Right links for user info navbar -->
                <ul class="user-info-menu right-links list-inline list-unstyled">

                    <li class="dropdown user-profile">
                        <a href="#" data-toggle="dropdown">
                            <img src="/assets/images/user-4.png" alt="user-image" class="img-circle img-inline userpic-32" width="28" />
                            <span>
								Администратор
								<i class="fa-angle-down"></i>
							</span>
                        </a>

                        <ul class="dropdown-menu user-profile-menu list-unstyled">
                            <li>
                                <a href="#edit-profile">
                                    <i class="fa-edit"></i>
                                    New Post
                                </a>
                            </li>
                            <li>
                                <a href="#settings">
                                    <i class="fa-wrench"></i>
                                    Settings
                                </a>
                            </li>
                            <li>
                                <a href="#profile">
                                    <i class="fa-user"></i>
                                    Profile
                                </a>
                            </li>
                            <li>
                                <a href="#help">
                                    <i class="fa-info"></i>
                                    Help
                                </a>
                            </li>
                            <li class="last">
                                <a href="/logout">
                                    <i class="fa-lock"></i>
                                    Выход
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>

            </nav>

            <?=$this->content; ?>

            <!-- Main Footer -->
            <!-- Choose between footer styles: "footer-type-1" or "footer-type-2" -->
            <!-- Add class "sticky" to  always stick the footer to the end of page (if page contents is small) -->
            <!-- Or class "fixed" to  always fix the footer to the end of page -->
            <footer class="main-footer sticky footer-type-1">

                <div class="footer-inner">

                    <!-- Add your copyright text here -->
                    <div class="footer-text">
                        &copy; 2017
                        <strong>Redl</strong>
                    </div>


                    <!-- Go to Top Link, just add rel="go-top" to any link to add this functionality -->
                    <div class="go-up">

                        <a href="#" rel="go-top">
                            <i class="fa-angle-up"></i>
                        </a>

                    </div>

                </div>

            </footer>

        </div>




    </div>






    <!-- Bottom Scripts -->
    <?= $this->inlineScript()
        ->appendFile($this->basePath('/assets/js/bootstrap.min.js'))
        ->appendFile($this->basePath('/assets/js/tweenmax.min.js'))
        ->appendFile($this->basePath('/assets/js/resizeable.js'))
        ->appendFile($this->basePath('/assets/js/joinable.js'))
        ->appendFile($this->basePath('/assets/js/xenon-api.js'))
        ->appendFile($this->basePath('/assets/js/xenon-toggles.js'))
//        ->appendFile($this->basePath('/assets/js/jquery.bootstrap.wizard.min.js'))
//        ->appendFile($this->basePath('/assets/js/jquery-ui/jquery-ui.min.js'))
        ->appendFile($this->basePath('/assets/js/xenon-custom.js'))
        ->appendFile("https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js")
    ?>


    <!-- JavaScripts initializations and stuff -->
    <script src="/assets/js/xenon-common.js"></script>

    </body>

</html>
