
<!--ADDING THE REQUIRED STYLE SHEETS-->

<link type="text/css" href="/css/bootstrap.css" rel="stylesheet">  <!--BOOTSTRAP 3 CSS FILE-->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'> <!-- Google web font link-->
<link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> <!--Font Awesome CSS FILE-->
<link type="text/css" href="/css/custom.css" rel="stylesheet">  <!--CUSTOM CSS FILE-->
<link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">  <!--animate.css FILE-->



<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->


<section>
    <div class="container">
        <div class="row row1">
            <div class="col-md-12">
                <h3 class="center capital f1 wow fadeInLeft" data-wow-duration="2s">Что то пошло не так!</h3>
                <h1 id="error" class="center wow fadeInRight" data-wow-duration="2s">0</h1>
                <p class="center wow bounceIn" data-wow-delay="2s">Страница не найдена!</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div id="cflask-holder" class="wow fadeIn" data-wow-delay="2800ms">
                            <span class="wow tada " data-wow-delay="3000ms"><i class="fa fa-flask fa-5x flask wow flip" data-wow-delay="3300ms"></i>
                                <i id="b1" class="bubble"></i>
                                <i id="b2" class="bubble"></i>
                                <i id="b3" class="bubble"></i>

                            </span>
                </div>
            </div>
        </div>
    </div>
</section>

<!--ADDING THE REQUIRED SCRIPT FILES-->
<!--<script type="text/javascript" src="/js/jquery-3.1.0.min.js"></script>-->
<script type="text/javascript" src="/public/js/countUp.js"></script>
<script type="text/javascript" src="/public/js/wow.js"></script>

<!--Initiating the CountUp Script-->
<script type="text/javascript">
    "use strict";
    var count = new countUp("error", 0, 404, 0, 3);

    window.onload = function() {
        // fire animation
        count.start();
    }
</script>

<!--Initiating the Wow Script-->
<script>
    $(document).ready(function () {
        "use strict";
        var wow = new WOW(
            {
                animateClass: 'animated',
                offset:       100
            }
        );
        wow.init();
    });

</script>


