<?= $this->doctype() ?>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Redl')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/slick.css'))
        ->prependStylesheet($this->basePath('lib/pswp//default-skin/default-skin.css'))
        ->prependStylesheet($this->basePath('lib/pswp/photoswipe.css'))
        ->prependStylesheet($this->basePath('assets/css/pages/listing/media.css'))
            ->prependStylesheet($this->basePath('assets/css/pages/listing/main.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Lato:300,400|Roboto+Condensed:300,400" rel="stylesheet"')
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
//        ->prependStylesheet($this->basePath('css/bootstrap.full.min.css'))
        ->prependStylesheet($this->basePath('lib/font-awesome-4.7.0/css/font-awesome.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('assets/js/pages/listing/script.js'))
        ->prependFile($this->basePath('lib/pswp/photoswipe-ui-default.min.js'))
        ->prependFile($this->basePath('lib/pswp/photoswipe.min.js'))
        ->prependFile($this->basePath('js/slick.min.js'))
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js')
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-105099017-1', 'auto');
        ga('send', 'pageview');

    </script>
</head>
<body>
<style>
    /* Sticky footer styles
-------------------------------------------------- */
    html {
        position: relative;
        min-height: 100%;
    }
    body {
        margin-bottom: 60px; /* Margin bottom by footer height */
    }
    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 60px; /* Set the fixed height of the footer here */
        line-height: 60px; /* Vertically center the text there */
    }
</style>
<main>
<header>
    <div class="container">
        <?= $this->partial('application/partial/red-head');?>
    </div>
</header>
<?= $this->content ?>
</main>
<footer class="footer">
    <div class="container">
        <p>&copy; 2005 - <?= date('Y') ?> by Redl Ltd. All rights reserved.</p>

    </div>
</footer>

<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

    <!-- Background of PhotoSwipe.
         It's a separate element as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>

    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">

        <!-- Container that holds slides.
            PhotoSwipe keeps only 3 of them in the DOM to save memory.
            Don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <!--  Controls are self-explanatory. Order can be changed. -->

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                <button class="pswp__button pswp__button--share" title="Share"></button>

                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
            </div>

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>

            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>

            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>

        </div>

    </div>

</div>

<?= $this->inlineScript() ?>
</body>
</html>
