<?= $this->doctype() ?>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Redl')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('assets/css/pages/listing/media.css'))
        ->prependStylesheet($this->basePath('assets/css/pages/listing/main.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Lato:300,400|Roboto+Condensed:300,400" rel="stylesheet"')
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('lib/font-awesome-4.7.0/css/font-awesome.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js')
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<header>
    <div class="container">
        <?= $this->partial('application/partial/red-head',['activeMenuItem'=>$this->activeMenuItem]);?>
    </div>
</header>

<?= $this->content ?>

<footer class="footer">
    <div class="container">
        <p>&copy; 2005 - <?= date('Y') ?> by Redl Ltd. All rights reserved.</p>

    </div>
</footer>
<?= $this->inlineScript() ?>
</body>
</html>
