<!DOCTYPE html>
<html>
<head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <title>Раздел в разработке</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('lib/under-const/css/style.css'))
        ->prependStylesheet($this->basePath('assets/css/pages/listing/media.css'))
        ->prependStylesheet($this->basePath('assets/css/pages/listing/main.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <link href='https://fonts.googleapis.com/css?family=Finger+Paint' rel='stylesheet' type='text/css'>
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('lib/under-const/js/script.js'))
        ->prependFile($this->basePath('lib/under-const/js/jquery-animate-css-rotate-scale.js'))
        ->prependFile($this->basePath('lib/under-const/js/jquery.spritely-0.6.1.js'))
        ->prependFile($this->basePath('lib/under-const/js/plax.js'))
        ->prependFile($this->basePath('lib/under-const/js/css_browser_selector.js'))
        ->prependFile($this->basePath('lib/under-const/js/preloader.js'))
        ->prependFile($this->basePath('lib/under-const/js/jquery-1.8.3.min.js'))
    ?>
</head>
<body >
<div id="indicator"></div>
<header>
    <div class="container">
        <?= $this->partial('application/partial/red-head',['activeMenuItem'=>$this->activeMenuItem]);?>
    </div>
</header>

<div style="overflow: hidden" class="wrapper">
    <div class="sky init">
        <div id="clouds" class="clouds init"> </div>
    </div>

    <div class="convas init">
        <div id="mountain" class="mountain"></div>
        <div class="ground"></div>
        <div class="holder">
            <div class="rocks"></div>
            <div class="work-sign"></div>
            <div class="text-sign">
                <div style="font-family: sans-serif" class="text font">

                    Этот раздел находится в разработке

                </div>
            </div>
            <div class="init hole">
                <div class="sweat"></div>
                <div class="worker swing "></div>
                <div class="ground-bottom">
                    <div class="cleaner"></div>
                </div>
            </div>
        </div>
    </div>


</div>


</body>
</html>
