<?php
//$previous =
//?>
<?php if ($this->pageCount > 1): ?>
    <nav class="text-center">
        <ul class="pagination">

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?= preg_replace('/%5B\d%5D/','',$this->url($this->route, ['action' => 'index', 'd_type' => $this->d_type,'p_type' => $this->p_type, 'city' => $this->city], ['query'=>array_merge($this->query,['page'=>$this->previous])])); ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&laquo;</span>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?= preg_replace('/%5B\d%5D/','',$this->url($this->route, ['action' => 'index', 'd_type' => $this->d_type,'p_type' => $this->p_type, 'city' => $this->city], ['query'=>array_merge($this->query,['page'=>$page])])); ?>"><?= $this->escapeHtml($page); ?></a>
                    </li>
                <?php else: ?>
                    <li>
                        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo preg_replace('/%5B\d%5D/','',$this->url($this->route, ['action' => 'index', 'd_type' => $this->d_type,'p_type' => $this->p_type, 'city' => $this->city], ['query'=>array_merge($this->query,['page'=>$this->next])])); ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>