<header>
    <div class="container">
        <div class="row top-line">
            <div class="col-xs-12 col-sm-3">
                <div class="mnu_wrap">
                    <button class="toggle_mnu">
					<span class="sandwich">
						<span class="sw-topper"></span>
						<span class="sw-bottom"></span>
						<span class="sw-footer"></span>
					</span>
                    </button>
                </div>
                <div class="logo_wrap">
                    <a href="/">
                        <img src="/assets/images/mblogo.white.png" alt="АН Редл"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-sm-9">
                <nav>
                    <ul>
                        <li><a href="/prodazha-kvartir-kiev">Продажа</a></li>
                        <li><a href="/arenda-kvartir-kiev">Аренда</a></li>
                        <li><a href="/newhouse">Новостройки</a></li>
                        <li><a href="/news">Новости</a></li>
                        <li><a href="/contacts">Контакты</a></li>
                        <li><i class="fa fa-user-o" aria-hidden="true"></i> <a href="/login">Вход</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="row search_line">
            <div class="col-md-12">
                <h1 class="hidden-xs hidden-sm">Продажа и аренда недвижимости в Киеве</h1>
                <p class="hidden-xs hidden-sm">233444 объявлений о продаже и аренде жилой, загородной и коммерческой недвижимости</p>
                <div class="search_wrap x-select-wrap row">
                    <div class="x-select-item-wrap col-xs-12 col-sm-4 col-md-2 nopadding">
                        <div value="prodazha" class="x-select">Продажа</div>
                        <div class="x-select-tt">
                            <div data-value="prodazha" class="x-select-tt-item  hovered checked">Продажа</div>
                            <div data-value="arenda" class="x-select-tt-item">Аренда</div>
                        </div>
                    </div>
                    <div class="x-select-item-wrap col-xs-12 col-sm-4 col-md-2 nopadding">
                        <div value="kvartir" class="x-select">Квартира</div>
                        <div class="x-select-tt">
                            <div data-value="kvartir" class="x-select-tt-item hovered checked">Квартира</div>
                            <div data-value="komnat" class="x-select-tt-item">Комната</div>
                            <div data-value="domov" class="x-select-tt-item">Дом</div>
                        </div>
                    </div>
                    <div class="x-select-item-wrap col-xs-12 col-sm-4 col-md-2 nopadding">
                        <div value="kiev" class="x-select">Киев</div>
                    </div>
                    <div data-default="Комнат" class="x-select-item-wrap col-xs-12 col-sm-4 col-md-2 nopadding checker">
                        <div value="null" class="x-select">Комнат</div>
                        <div class="x-select-tt">
                            <div data-value="1" class="x-select-tt-item">1-комнатная</div>
                            <div data-value="2" class="x-select-tt-item">2-комнатная</div>
                            <div data-value="3" class="x-select-tt-item">3-комнатная</div>
                            <div data-value="4" class="x-select-tt-item">4-комнатная</div>
                            <div data-value="5" class="x-select-tt-item">5-комнатная</div>
                            <div data-value="6" class="x-select-tt-item">6-комнатная +</div>
                        </div>
                    </div>
                    <div id="price" class="x-select-item-wrap col-xs-8 col-sm-4 col-md-2 nopadding">
                        <div class="x-select">Цена</div>
                        <div class="adv_select-tt x-select-tt">
                            <div class="adv_select_inputs">
                                <input type="text" class="adv_from" id="price_from" name="price_from" placeholder="От">
                                <span>—</span>
                                <input type="text" class="adv_to" id="price_to" name="price_to" placeholder="До">
                            </div>
                            <ul>
                                <li>4 000</li>
                                <li>6 000</li>
                                <li>8 000</li>
                                <li>10 000</li>
                                <li>12 000</li>
                                <li>14 000</li>
                            </ul>
                        </div>
                    </div>
                    <div id="swiper" class="x-select-item-wrap col-xs-4 col-sm-2 col-md-1 nopadding">
                        <div>UAH</div>
                    </div>
                    <a style="display: block;" class="s_link" href="/prodazha-kvartir-kiev">
                    <div id="sb" class="x-select-item-wrap col-xs-12 col-sm-2 col-md-1 nopadding">
                        <div><i class="fa fa-search" aria-hidden="true"></i></div>
                    </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="s_tiles">
    <div class="container">
        <div class="row tileset">
            <div class="col-xs-12 col-md-6">
                <div class="row tile_wrap">
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-img-wrap">
                            <img src="/assets/images/tile1-min.jpg" alt="Купить квартиру">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-info">
                            <p>Купить квартиру</p>
                            <ul>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=1">1-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=2">2-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=3">3-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=4">4-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=5">5-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/prodazha-kvartir-kiev?rooms=6">6-комнатные+</a>
                                    <span>42 045</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="row tile_wrap tile-rent">
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-img-wrap">
                            <img style="min-height: 152px;" src="/assets/images/tile2-min.jpg" alt="Купить квартиру">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-info">
                            <p>Снять квартиру</p>
                            <ul>
                                <li>
                                    <a href="/arenda-kvartir-kiev?rooms=1">1-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/arenda-kvartir-kiev?rooms=1">2-комнатные</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="/arenda-kvartir-kiev?rooms=1">3-комнатные</a>
                                    <span>42 045</span>
                                </li>
<!--                                <li>-->
<!--                                    <a href="#">Квартиры-студии</a>-->
<!--                                    <span>42 045</span>-->
<!--                                </li>-->
                                <li>
                                    <a href="/arenda-komnat-kiev">Комнаты в квартире</a>
                                    <span>42 045</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row tileset">
            <div class="col-xs-12 col-md-6">
                <div class="row tile_wrap">
                    <div class="col-xs-12 col-sm-6 col-md-push-6 nopadding">
                        <div class="tile-img-wrap">
                            <img src="/assets/images/tile3-min.jpg" alt="Купить квартиру">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-pull-6 nopadding">
                        <div class="tile-info">
                            <p>Снять посуточно</p>
                            <ul>
                                <li>
                                    <a href="#">Квартиры посуточно</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Коттеджи на сутки</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Комнаты на сутки</a>
                                    <span>42 045</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3">
                <div class="row tile_wrap tile-new">
                    <div class="col-xs-12  nopadding">
                        <div class="tile-info">
                            <p>Новостройки</p>
                            <ul>
                                <li>
                                    <a href="#">Каталог ЖК</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Сданные новостройки</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Строящиеся новостройки</a>
                                    <span>42 045</span>
                                </li>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-3" >
                <div class="row tile_wrap tile-vilage">
                    <div class="col-xs-12  nopadding">
                        <div class="tile-info">
                            <p>Загородная недвижимость</p>
                            <ul>
                                <li>
                                    <a href="#">Купить дом</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Купить таунхаус</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Купить участок</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Снять дом надолго</a>
                                    <span>42 045</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row tileset">
            <div class="col-xs-12 col-md-6">
                <div class="row tile_wrap">
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-img-wrap">
                            <img src="/assets/images/tile4-min.jpg" alt="Купить квартиру">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 nopadding">
                        <div class="tile-info">
                            <p>Коммерческая недвижимость</p>
                            <ul>
                                <li>
                                    <a href="#">Купить склад</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Купить гараж</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Купить офис</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Арендовать офис</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Арендовать помещение</a>
                                    <span>42 045</span>
                                </li>
                                <li>
                                    <a href="#">Арендовать торговую площадь</a>
                                    <span>42 045</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6" >
                <div class="row tile_wrap tile-map">
                    <div class="col-xs-12 nopadding">
                        <div class="tile-map">
                            <img src="/assets/images/map-min.png" alt="Редл">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="s_popular hidden-lg-down">
    <div class="container">
        <h3>Популярные объявления</h3>
        <div class="row">
            <div class="col-xs-12 filter_wrap">
                <ul>
                    <li><a href="#" class="f1 mixitup-control-active" data-filter=".s1">Продажа</a></li>
                    <li><a href="#" class="f1" data-filter=".s2">Аренда</a></li>
                </ul>
            </div>
            <div class="col-xs-12 ">
                <div id="mixer1" class="row cwr">
                    <div class="col-xs-12 col-md-4 cw mix s1">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">100 000 $</p>
                                        <p class="det">3-комн. кв., 140 м</p>
                                        <p class="metro" data-line="1">Крещатик</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 cw mix s1">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">70 000 $</p>
                                        <p class="det">2-комн. кв., 140 м</p>
                                        <p class="metro" data-line="2">Кловская</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 cw mix s1">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">50 000 $</p>
                                        <p class="det">1-комн. кв., 140 м</p>
                                        <p class="metro" data-line="3">Оболонь</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="col-xs-12 col-md-4 cw mix s2">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">100 000 $</p>
                                        <p class="det">3-комн. кв., 140 м</p>
                                        <p class="metro" data-line="1">Крещатик</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 cw mix s2">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">70 000 $</p>
                                        <p class="det">2-комн. кв., 140 м</p>
                                        <p class="metro" data-line="2">Кловская</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 cw mix s2">
                        <div class="card_wrap">
                            <a href="#">
                                <div class="card">
                                    <div class="img_wrap">
                                        <img src="/assets/uploads/listing-images/123/ava1-min.jpg">
                                    </div>
                                    <div class="info">
                                        <p class="price">50 000 $</p>
                                        <p class="det">1-комн. кв., 140 м</p>
                                        <p class="metro" data-line="3">Оболонь</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<section class="s_text" style="background: #fff;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h4>Поиск недвижимости на REDL</h4>
            </div>
            <div class="col-xs-12 col-md-4">
                <p>
                    <b>Риэлторская компания</b> Redl занимается продажей всех видов недвижимости в Киеве и области. При
                    желании
                    продать или приобрести коттедж, квартиру, комнату, гараж, дачу, офис или производственную площадку,
                    обращайтесь к нам. В <b>агентстве недвижимости</b> Redl трудятся профессионалы, которые обладают
                    обширными
                    знаниями и опытом, работают на совесть и стремятся сделать все возможное, чтобы клиент остался
                    доволен.
                    Оформление сделок с дорогостоящей собственностью требует кропотливой работы и ответственного
                    отношения, любой промах может обернуться потерей репутации и значительными финансовыми потерями.
                    Наши клиенты нам доверяют, и мы очень это ценим.

                </p>
            </div>
            <div class="col-xs-12 col-md-4">
                <p>
                    <b>Когда стоит обращаться в риэлторскою компанию?</b>
                    Среднестатистический гражданин совершает сделки с недвижимостью всего несколько раз в жизни. Вместе
                    с тем, законодательство меняется регулярно, да и сложно непрофессионалу разобраться в хитросплетении
                    формулировок и статей.
                    Специалисты советуют заручаться помощью профессионалов каждый раз, когда вы совершаете сделку, в
                    которой каким-либо образом фигурирует ваша квартира, офис или дача. Лучше лишний раз сходить на
                    консультацию и заручиться мнением специалиста, чем обнаружить, что имуществом завладели мошенники.

                </p>
            </div>
            <div>
                <p class="without-title">
                    <b>Киевская риэлторская компания</b> Redl обладает также всеми необходимыми по закону документами,
                    лицензиями и сертификатами, которые подтверждают законность и высокий профессиональный уровень нашей
                    деятельности.
                    На вооружении наших сотрудников есть все необходимые технические средства для того, чтобы выполнять
                    свою работу быстро, грамотно и качественно. Информационные базы пополняются регулярно и
                    своевременно, мы работаем с самой свежей информацией.

                </p>
            </div>
        </div>
    </div>
</section>
<section class="s_links">
    <div class="container">
        <div class="row subway">
            <div class="col-xs-12">
                <h5>
                    Квартиры у метро
                </h5>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Академгородок</a></li>
                    <li><a href="#">Арсенальная</a></li>
                    <li><a href="#">Берестейская</a></li>
                    <li><a href="#">Бориспольская</a></li>
                    <li><a href="#">Васильковская</a></li>
                    <li><a href="#">Выдубичи</a></li>
                    <li><a href="#">Вырлица</a></li>
                    <li><a href="#">Выставочный центр</a></li>
                    <li><a href="#">Героев Днепра</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Гидропарк</a></li>
                    <li><a href="#">Голосеевская</a></li>
                    <li><a href="#">Дарница</a></li>
                    <li><a href="#">Дворец спорта</a></li>
                    <li><a href="#">Дворец Украина</a></li>
                    <li><a href="#">Демиевская</a></li>
                    <li><a href="#">Днепр</a></li>
                    <li><a href="#">Дорогожичи</a></li>
                    <li><a href="#">Дружбы народов</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Житомирская</a></li>
                    <li><a href="#">Золотые ворота</a></li>
                    <li><a href="#">Ипподром</a></li>
                    <li><a href="#">Кловская</a></li>
                    <li><a href="#">Контрактовая площадь</a></li>
                    <li><a href="#">Красный хутор</a></li>
                    <li><a href="#">Крещатик</a></li>
                    <li><a href="#">Левобережная</a></li>
                    <li><a href="#">Лесная</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Лукьяновская</a></li>
                    <li><a href="#">Лыбедская</a></li>
                    <li><a href="#">Минская</a></li>
                    <li><a href="#">Нивки</a></li>
                    <li><a href="#">Оболонь</a></li>
                    <li><a href="#">Олимпийская</a></li>
                    <li><a href="#">Осокорки</a></li>
                    <li><a href="#">Петровка</a></li>
                    <li><a href="#">Печерская</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Площадь Льва Толстого</a></li>
                    <li><a href="#">Площадь Независимости</a></li>
                    <li><a href="#">Позняки</a></li>
                    <li><a href="#">Политех. институт</a></li>
                    <li><a href="#">Почтовая площадь</a></li>
                    <li><a href="#">Святошин</a></li>
                    <li><a href="#">Славутич</a></li>
                    <li><a href="#">Сырец</a></li>
                    <li><a href="#">Тараса Шевченко</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <ul>
                    <li><a href="#">Теремки</a></li>
                    <li><a href="#">Университет</a></li>
                    <li><a href="#">Харьковская</a></li>
                    <li><a href="#">Черниговская</a></li>
                    <li><a href="#">Шулявская</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
